FROM node:19-alpine3.15

RUN npm install -g --unsafe-perm prisma

WORKDIR /back
COPY ./backend/package.json ./backend/package-lock.json ./
COPY ./backend/prisma ./prisma
RUN npm install
RUN prisma generate

RUN chmod -R 777 ./node_modules
